### ISSUE TITLE
Allow use domain names in dadrr/saddr rules

### ISSUE THREAD

**Issue by rgomezceis** [capnspacehook/whalewall#38]
nftables allow the use of domain names in daddr/saddr
Some services like azure has a lot of ip addresses for a single domain name, so with this we don't need to allow all the IP addresses manually anymore.

**Comment by capnspacehook** [comment]
nftables does indeed allow users to specify domain names, but it doesn't work the way you'd expect. nftables rules don't support domain names, only IP addresses so when rules are created nftables does a DNS lookup of the domain and uses the returned IP in the created rules.

This is often not what you want. Like you said, due to load balancers lookups for the same domain can return different IPs, or IPs can simply change over time. I created a separate tool to solve this problem that I use with whalewall: https://github.com/capnspacehook/egress-eddie. Egress Eddie only allows DNS requests to allowed hostnames, and then only allows traffic to IPs returned by allowed DNS lookups. 

Note that while Egress Eddie does have a Docker container in the master branch, I can't get it to pass tests for some unknown reason. I suspect it's a downstream issue with one of my deps or Docker itself. So you'll have to run it natively for now.
